// screen_writer_single_cycle - auto-generated by gen_screen_writer.py
// Character-level round-robin.  Refresh = 111 cycles @ 50 MHz.

module screen_writer_single_cycle (
    input logic        clk,
    input logic        rst_n,

    // Processor signals (all values to be displayed)
    input logic [31:0] alu_a,
    input logic [31:0] alu_b,
    input logic [4:0] alu_op,
    input logic [31:0] alu_res,
    input logic [1:0] alua_src,
    input logic [0:0] alub_src,
    input logic [4:0] br_op,
    input logic [0:0] branch,
    input logic [31:0] data_wr,
    input logic [31:0] dm_addr,
    input logic [2:0] dm_ctrl,
    input logic [0:0] dm_wr,
    input logic [2:0] funct3,
    input logic [6:0] funct7,
    input logic [31:0] imm_out,
    input logic [2:0] imm_src,
    input logic [31:0] instruction,
    input logic [31:0] next_pc,
    input logic [6:0] opcode,
    input logic [31:0] pc,
    input logic [4:0] rd_addr,
    input logic [4:0] rs1_addr,
    input logic [31:0] rs1_data,
    input logic [4:0] rs2_addr,
    input logic [31:0] rs2_data,
    input logic [1:0] ru_data_wr_src,
    input logic [0:0] ru_wr,

    // Video memory port (write-only, processor clock domain)
    output logic        vmem_wr_en,
    output logic [12:0] vmem_wr_addr,
    output logic [15:0] vmem_wr_data
);

    // -----------------------------------------------------------------------
    // Field address map (from fields.json)
    // -----------------------------------------------------------------------
    localparam int ADDR_PC = 13'd859;
    localparam int ADDR_INSTRUCTION = 13'd1019;
    localparam int ADDR_NEXT_PC = 13'd1179;
    localparam int ADDR_BRANCH = 13'd1339;
    localparam int ADDR_RS1_ADDR = 13'd2456;
    localparam int ADDR_RS2_ADDR = 13'd2464;
    localparam int ADDR_RD_ADDR = 13'd2471;
    localparam int ADDR_RU_DATA_WR_SRC = 13'd2495;
    localparam int ADDR_DATA_WR = 13'd2779;
    localparam int ADDR_RU_WR = 13'd2795;
    localparam int ADDR_RS1_DATA = 13'd3260;
    localparam int ADDR_RS2_DATA = 13'd3420;
    localparam int ADDR_IMM_OUT = 13'd3736;
    localparam int ADDR_IMM_SRC = 13'd3754;
    localparam int ADDR_DM_ADDR = 13'd3934;
    localparam int ADDR_OPCODE = 13'd4060;
    localparam int ADDR_FUNCT3 = 13'd4072;
    localparam int ADDR_FUNCT7 = 13'd4220;
    localparam int ADDR_DM_CTRL = 13'd4414;
    localparam int ADDR_DM_WR = 13'd4574;
    localparam int ADDR_ALU_A = 13'd5339;
    localparam int ADDR_ALU_B = 13'd5499;
    localparam int ADDR_ALU_RES = 13'd5659;
    localparam int ADDR_ALU_OP = 13'd5978;
    localparam int ADDR_BR_OP = 13'd5988;
    localparam int ADDR_ALUA_SRC = 13'd6140;
    localparam int ADDR_ALUB_SRC = 13'd6151;

    localparam int N_CHARS = 111;
    localparam int CTR_W     = 7;

    logic [6:0] char_ctr;

    // -----------------------------------------------------------------------
    // Helper functions: value --> ASCII
    // -----------------------------------------------------------------------
    function automatic [7:0] hex_digit (
        input logic [31:0] value,
        input int          nibble
    );
        logic [3:0] d;
        d = (value >> (nibble * 4)) & 4'hF;
        hex_digit = (d < 4'd10) ? (8'd48 + d) : (8'd55 + d);  // '0'-'9', 'A'-'F'
    endfunction

    function automatic [7:0] bin_digit (
        input logic value,
        input int   bit_idx
    );
        bin_digit = 8'd48 + ((value >> bit_idx) & 1'b1);  // '0' or '1'
    endfunction

    // -----------------------------------------------------------------------
    // Round-robin FSM - one char per cycle
    // -----------------------------------------------------------------------
    logic        wr_en;
    logic [12:0] wr_addr;
    logic [7:0]  wr_data;

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            char_ctr <= '0;
        end else begin
            char_ctr <= (char_ctr == N_CHARS - 1) ? '0 : char_ctr + 1'b1;
        end
    end

    always_comb begin
        // Default: no write
        wr_en   = 1'b0;
        wr_addr = '0;
        wr_data = 8'h20;  // space

        unique case (char_ctr)
        0: begin wr_en = 1'b1; wr_addr = ADDR_PC + 0; wr_data = hex_digit(pc, 7); end
        1: begin wr_en = 1'b1; wr_addr = ADDR_PC + 1; wr_data = hex_digit(pc, 6); end
        2: begin wr_en = 1'b1; wr_addr = ADDR_PC + 2; wr_data = hex_digit(pc, 5); end
        3: begin wr_en = 1'b1; wr_addr = ADDR_PC + 3; wr_data = hex_digit(pc, 4); end
        4: begin wr_en = 1'b1; wr_addr = ADDR_PC + 4; wr_data = hex_digit(pc, 3); end
        5: begin wr_en = 1'b1; wr_addr = ADDR_PC + 5; wr_data = hex_digit(pc, 2); end
        6: begin wr_en = 1'b1; wr_addr = ADDR_PC + 6; wr_data = hex_digit(pc, 1); end
        7: begin wr_en = 1'b1; wr_addr = ADDR_PC + 7; wr_data = hex_digit(pc, 0); end
        8: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 0; wr_data = hex_digit(instruction, 7); end
        9: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 1; wr_data = hex_digit(instruction, 6); end
        10: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 2; wr_data = hex_digit(instruction, 5); end
        11: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 3; wr_data = hex_digit(instruction, 4); end
        12: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 4; wr_data = hex_digit(instruction, 3); end
        13: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 5; wr_data = hex_digit(instruction, 2); end
        14: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 6; wr_data = hex_digit(instruction, 1); end
        15: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 7; wr_data = hex_digit(instruction, 0); end
        16: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 0; wr_data = hex_digit(next_pc, 7); end
        17: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 1; wr_data = hex_digit(next_pc, 6); end
        18: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 2; wr_data = hex_digit(next_pc, 5); end
        19: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 3; wr_data = hex_digit(next_pc, 4); end
        20: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 4; wr_data = hex_digit(next_pc, 3); end
        21: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 5; wr_data = hex_digit(next_pc, 2); end
        22: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 6; wr_data = hex_digit(next_pc, 1); end
        23: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 7; wr_data = hex_digit(next_pc, 0); end
        24: begin wr_en = 1'b1; wr_addr = ADDR_BRANCH + 0; wr_data = bin_digit(branch, 0); end
        25: begin wr_en = 1'b1; wr_addr = ADDR_RS1_ADDR + 0; wr_data = hex_digit(rs1_addr, 1); end
        26: begin wr_en = 1'b1; wr_addr = ADDR_RS1_ADDR + 1; wr_data = hex_digit(rs1_addr, 0); end
        27: begin wr_en = 1'b1; wr_addr = ADDR_RS2_ADDR + 0; wr_data = hex_digit(rs2_addr, 1); end
        28: begin wr_en = 1'b1; wr_addr = ADDR_RS2_ADDR + 1; wr_data = hex_digit(rs2_addr, 0); end
        29: begin wr_en = 1'b1; wr_addr = ADDR_RD_ADDR + 0; wr_data = hex_digit(rd_addr, 1); end
        30: begin wr_en = 1'b1; wr_addr = ADDR_RD_ADDR + 1; wr_data = hex_digit(rd_addr, 0); end
        31: begin wr_en = 1'b1; wr_addr = ADDR_RU_DATA_WR_SRC + 0; wr_data = hex_digit(ru_data_wr_src, 0); end
        32: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 0; wr_data = hex_digit(data_wr, 7); end
        33: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 1; wr_data = hex_digit(data_wr, 6); end
        34: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 2; wr_data = hex_digit(data_wr, 5); end
        35: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 3; wr_data = hex_digit(data_wr, 4); end
        36: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 4; wr_data = hex_digit(data_wr, 3); end
        37: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 5; wr_data = hex_digit(data_wr, 2); end
        38: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 6; wr_data = hex_digit(data_wr, 1); end
        39: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 7; wr_data = hex_digit(data_wr, 0); end
        40: begin wr_en = 1'b1; wr_addr = ADDR_RU_WR + 0; wr_data = bin_digit(ru_wr, 0); end
        41: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 0; wr_data = hex_digit(rs1_data, 7); end
        42: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 1; wr_data = hex_digit(rs1_data, 6); end
        43: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 2; wr_data = hex_digit(rs1_data, 5); end
        44: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 3; wr_data = hex_digit(rs1_data, 4); end
        45: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 4; wr_data = hex_digit(rs1_data, 3); end
        46: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 5; wr_data = hex_digit(rs1_data, 2); end
        47: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 6; wr_data = hex_digit(rs1_data, 1); end
        48: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 7; wr_data = hex_digit(rs1_data, 0); end
        49: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 0; wr_data = hex_digit(rs2_data, 7); end
        50: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 1; wr_data = hex_digit(rs2_data, 6); end
        51: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 2; wr_data = hex_digit(rs2_data, 5); end
        52: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 3; wr_data = hex_digit(rs2_data, 4); end
        53: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 4; wr_data = hex_digit(rs2_data, 3); end
        54: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 5; wr_data = hex_digit(rs2_data, 2); end
        55: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 6; wr_data = hex_digit(rs2_data, 1); end
        56: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 7; wr_data = hex_digit(rs2_data, 0); end
        57: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 0; wr_data = hex_digit(imm_out, 7); end
        58: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 1; wr_data = hex_digit(imm_out, 6); end
        59: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 2; wr_data = hex_digit(imm_out, 5); end
        60: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 3; wr_data = hex_digit(imm_out, 4); end
        61: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 4; wr_data = hex_digit(imm_out, 3); end
        62: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 5; wr_data = hex_digit(imm_out, 2); end
        63: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 6; wr_data = hex_digit(imm_out, 1); end
        64: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 7; wr_data = hex_digit(imm_out, 0); end
        65: begin wr_en = 1'b1; wr_addr = ADDR_IMM_SRC + 0; wr_data = hex_digit(imm_src, 0); end
        66: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 0; wr_data = hex_digit(dm_addr, 7); end
        67: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 1; wr_data = hex_digit(dm_addr, 6); end
        68: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 2; wr_data = hex_digit(dm_addr, 5); end
        69: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 3; wr_data = hex_digit(dm_addr, 4); end
        70: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 4; wr_data = hex_digit(dm_addr, 3); end
        71: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 5; wr_data = hex_digit(dm_addr, 2); end
        72: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 6; wr_data = hex_digit(dm_addr, 1); end
        73: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 7; wr_data = hex_digit(dm_addr, 0); end
        74: begin wr_en = 1'b1; wr_addr = ADDR_OPCODE + 0; wr_data = hex_digit(opcode, 1); end
        75: begin wr_en = 1'b1; wr_addr = ADDR_OPCODE + 1; wr_data = hex_digit(opcode, 0); end
        76: begin wr_en = 1'b1; wr_addr = ADDR_FUNCT3 + 0; wr_data = hex_digit(funct3, 0); end
        77: begin wr_en = 1'b1; wr_addr = ADDR_FUNCT7 + 0; wr_data = hex_digit(funct7, 1); end
        78: begin wr_en = 1'b1; wr_addr = ADDR_FUNCT7 + 1; wr_data = hex_digit(funct7, 0); end
        79: begin wr_en = 1'b1; wr_addr = ADDR_DM_CTRL + 0; wr_data = hex_digit(dm_ctrl, 0); end
        80: begin wr_en = 1'b1; wr_addr = ADDR_DM_WR + 0; wr_data = hex_digit(dm_wr, 0); end
        81: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 0; wr_data = hex_digit(alu_a, 7); end
        82: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 1; wr_data = hex_digit(alu_a, 6); end
        83: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 2; wr_data = hex_digit(alu_a, 5); end
        84: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 3; wr_data = hex_digit(alu_a, 4); end
        85: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 4; wr_data = hex_digit(alu_a, 3); end
        86: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 5; wr_data = hex_digit(alu_a, 2); end
        87: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 6; wr_data = hex_digit(alu_a, 1); end
        88: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 7; wr_data = hex_digit(alu_a, 0); end
        89: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 0; wr_data = hex_digit(alu_b, 7); end
        90: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 1; wr_data = hex_digit(alu_b, 6); end
        91: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 2; wr_data = hex_digit(alu_b, 5); end
        92: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 3; wr_data = hex_digit(alu_b, 4); end
        93: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 4; wr_data = hex_digit(alu_b, 3); end
        94: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 5; wr_data = hex_digit(alu_b, 2); end
        95: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 6; wr_data = hex_digit(alu_b, 1); end
        96: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 7; wr_data = hex_digit(alu_b, 0); end
        97: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 0; wr_data = hex_digit(alu_res, 7); end
        98: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 1; wr_data = hex_digit(alu_res, 6); end
        99: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 2; wr_data = hex_digit(alu_res, 5); end
        100: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 3; wr_data = hex_digit(alu_res, 4); end
        101: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 4; wr_data = hex_digit(alu_res, 3); end
        102: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 5; wr_data = hex_digit(alu_res, 2); end
        103: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 6; wr_data = hex_digit(alu_res, 1); end
        104: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 7; wr_data = hex_digit(alu_res, 0); end
        105: begin wr_en = 1'b1; wr_addr = ADDR_ALU_OP + 0; wr_data = hex_digit(alu_op, 1); end
        106: begin wr_en = 1'b1; wr_addr = ADDR_ALU_OP + 1; wr_data = hex_digit(alu_op, 0); end
        107: begin wr_en = 1'b1; wr_addr = ADDR_BR_OP + 0; wr_data = hex_digit(br_op, 1); end
        108: begin wr_en = 1'b1; wr_addr = ADDR_BR_OP + 1; wr_data = hex_digit(br_op, 0); end
        109: begin wr_en = 1'b1; wr_addr = ADDR_ALUA_SRC + 0; wr_data = hex_digit(alua_src, 0); end
        110: begin wr_en = 1'b1; wr_addr = ADDR_ALUB_SRC + 0; wr_data = bin_digit(alub_src, 0); end
            default: ;  // no write
        endcase
    end

    assign vmem_wr_en   = wr_en;
    assign vmem_wr_addr = wr_addr;
    assign vmem_wr_data = {8'h0F, wr_data};  // ATTR_DYNAMIC + char

endmodule
