# Timing constraints for rv32im on DE1-SoC (Cyclone V 5CSEMA5F31C6)
#
# Both microarchitectures use identical constraints to satisfy the
# homogeneous measurement protocol. Do not modify one without the other.
#
# Target: 100 MHz (10 ns period). This is intentionally aggressive so that
# Quartus reports the true achievable Fmax after place-and-route rather than
# stopping at an artificially relaxed target.

# ---------------------------------------------------------------------------
# Primary clock (processor clock)
# DE1-SoC provides a 50 MHz oscillator on PIN_AF14.
# ---------------------------------------------------------------------------
create_clock -period 10.000 -name clk [get_ports clk]

# ---------------------------------------------------------------------------
# VGA pixel clock (74.25 MHz generated by vga_pll from 50 MHz input)
# derive_pll_clocks auto-detects all PLL outputs regardless of the internal
# hierarchical path; wrap in a catch so the processor compiles without the
# visualization module (no PLL instantiated yet).
# ---------------------------------------------------------------------------
catch { derive_pll_clocks }

# ---------------------------------------------------------------------------
# Clock uncertainty
# Accounts for clock jitter on the Cyclone V device.
# ---------------------------------------------------------------------------
set_clock_uncertainty -rise_from [get_clocks clk] \
                      -rise_to   [get_clocks clk] 0.100
set_clock_uncertainty -fall_from [get_clocks clk] \
                      -fall_to   [get_clocks clk] 0.100

set vga_clk_name [get_clocks -nowarn *u_altpll*outclk*]
if {[llength $vga_clk_name] > 0} {
    set_clock_uncertainty -rise_from $vga_clk_name \
                          -rise_to   $vga_clk_name 0.150
    set_clock_uncertainty -fall_from $vga_clk_name \
                          -fall_to   $vga_clk_name 0.150

    # Asynchronous clock domain crossing - processor (50 MHz) and VGA (74.25 MHz)
    # operate in separate clock domains with no synchroniser.
    set_false_path -from [get_clocks clk] -to $vga_clk_name
    set_false_path -from $vga_clk_name -to [get_clocks clk]
}

# ---------------------------------------------------------------------------
# Input and output delays
# Conservative estimates for FPGA-internal paths; adjust when interfacing
# with external components (switches, LEDs, HEX displays on DE1-SoC).
# ---------------------------------------------------------------------------
set_input_delay  -clock clk -max 2.000 [get_ports {rst_n}]
set_input_delay  -clock clk -min 0.500 [get_ports {rst_n}]

# ---------------------------------------------------------------------------
# False paths
# Asynchronous inputs that do not require timing analysis.
# ---------------------------------------------------------------------------
# set_false_path -from [get_ports {KEY[0]}]  ;# uncomment when reset is on KEY
