// Generated by scripts/gen_mem_config.py - do not edit manually
`ifndef MEM_CONFIG_VH
`define MEM_CONFIG_VH

`define IMEM_FILE "/mnt/c/Users/juanb/Documents/GitHub/riscv-rv32im-fpga/build/imem.mem"
`define DMEM_FILE "/mnt/c/Users/juanb/Documents/GitHub/riscv-rv32im-fpga/build/dmem.mem"

`endif
