// Generated by scripts/gen_mem_config.py - do not edit manually
`ifndef MEM_CONFIG_VH
`define MEM_CONFIG_VH

`define IMEM_FILE "../../../build/imem.mem"
`define DMEM_FILE "../../../build/dmem.mem"

`endif
