// screen_writer_pipeline - auto-generated by gen_screen_writer.py
// Character-level round-robin.  Refresh = 267 cycles @ 50 MHz.

module screen_writer_pipeline (
    input logic        clk,
    input logic        rst_n,

    // Processor signals (all values to be displayed)
    input logic [31:0] alu_a,
    input logic [31:0] alu_b,
    input logic [4:0] alu_op,
    input logic [31:0] alu_res,
    input logic [4:0] br_op,
    input logic [0:0] branch,
    input logic [0:0] branch_flush,
    input logic [31:0] data_wr,
    input logic [31:0] dm_addr,
    input logic [2:0] dm_ctrl,
    input logic [31:0] dm_rdata,
    input logic [31:0] dm_wdata,
    input logic [0:0] dm_wr,
    input logic [31:0] ex_alu_result,
    input logic [0:0] ex_branch_taken,
    input logic [31:0] ex_imm,
    input logic [31:0] ex_instruction,
    input logic [31:0] ex_pc,
    input logic [31:0] ex_rs1_data,
    input logic [31:0] ex_rs2_data,
    input logic [0:0] flush,
    input logic [2:0] funct3,
    input logic [6:0] funct7,
    input logic [31:0] id_instruction,
    input logic [31:0] id_pc,
    input logic [31:0] if_instruction,
    input logic [31:0] if_pc,
    input logic [31:0] imm_out,
    input logic [2:0] imm_src,
    input logic [31:0] instruction,
    input logic [0:0] load_use_hazard,
    input logic [31:0] mem_alu_result,
    input logic [31:0] mem_instruction,
    input logic [31:0] mem_rs1_data,
    input logic [31:0] mem_rs2_data,
    input logic [31:0] next_pc,
    input logic [6:0] opcode,
    input logic [31:0] pc,
    input logic [4:0] rd_addr,
    input logic [4:0] rs1_addr,
    input logic [31:0] rs1_data,
    input logic [4:0] rs2_addr,
    input logic [31:0] rs2_data,
    input logic [1:0] ru_data_wr_src,
    input logic [0:0] ru_wr,
    input logic [0:0] stall,
    input logic [0:0] trap_flush,
    input logic [31:0] wb_instruction,
    input logic [4:0] wb_rd_addr,
    input logic [31:0] wb_rd_data,

    // Video memory port (write-only, processor clock domain)
    output logic        vmem_wr_en,
    output logic [12:0] vmem_wr_addr,
    output logic [15:0] vmem_wr_data
);

    // Field address map (from fields.json)
    localparam int ADDR_RU_DATA_WR_SRC = 13'd1198;
    localparam int ADDR_PC = 13'd1292;
    localparam int ADDR_RS1_ADDR = 13'd1316;
    localparam int ADDR_RS2_ADDR = 13'd1324;
    localparam int ADDR_RD_ADDR = 13'd1331;
    localparam int ADDR_INSTRUCTION = 13'd1452;
    localparam int ADDR_NEXT_PC = 13'd1612;
    localparam int ADDR_DATA_WR = 13'd1639;
    localparam int ADDR_RU_WR = 13'd1655;
    localparam int ADDR_IF_PC = 13'd1772;
    localparam int ADDR_IF_INSTRUCTION = 13'd1932;
    localparam int ADDR_BRANCH = 13'd2092;
    localparam int ADDR_RS1_DATA = 13'd2120;
    localparam int ADDR_RS2_DATA = 13'd2280;
    localparam int ADDR_MEM_ALU_RESULT = 13'd2314;
    localparam int ADDR_WB_INSTRUCTION = 13'd2474;
    localparam int ADDR_IMM_OUT = 13'd2596;
    localparam int ADDR_IMM_SRC = 13'd2614;
    localparam int ADDR_WB_RD_ADDR = 13'd2634;
    localparam int ADDR_WB_RD_DATA = 13'd2794;
    localparam int ADDR_OPCODE = 13'd2920;
    localparam int ADDR_FUNCT3 = 13'd2933;
    localparam int ADDR_FUNCT7 = 13'd3080;
    localparam int ADDR_ID_PC = 13'd3372;
    localparam int ADDR_ID_INSTRUCTION = 13'd3532;
    localparam int ADDR_DM_ADDR = 13'd4393;
    localparam int ADDR_EX_PC = 13'd4526;
    localparam int ADDR_DM_WDATA = 13'd4553;
    localparam int ADDR_EX_INSTRUCTION = 13'd4686;
    localparam int ADDR_DM_RDATA = 13'd4713;
    localparam int ADDR_EX_RS1_DATA = 13'd4846;
    localparam int ADDR_DM_CTRL = 13'd4873;
    localparam int ADDR_STALL = 13'd4977;
    localparam int ADDR_EX_RS2_DATA = 13'd5006;
    localparam int ADDR_DM_WR = 13'd5033;
    localparam int ADDR_LOAD_USE_HAZARD = 13'd5137;
    localparam int ADDR_EX_IMM = 13'd5166;
    localparam int ADDR_BRANCH_FLUSH = 13'd5297;
    localparam int ADDR_TRAP_FLUSH = 13'd5457;
    localparam int ADDR_FLUSH = 13'd5617;
    localparam int ADDR_ALU_A = 13'd6440;
    localparam int ADDR_MEM_RS1_DATA = 13'd6475;
    localparam int ADDR_ALU_B = 13'd6600;
    localparam int ADDR_MEM_RS2_DATA = 13'd6635;
    localparam int ADDR_ALU_RES = 13'd6760;
    localparam int ADDR_EX_ALU_RESULT = 13'd6795;
    localparam int ADDR_MEM_INSTRUCTION = 13'd6955;
    localparam int ADDR_ALU_OP = 13'd7079;
    localparam int ADDR_BR_OP = 13'd7089;
    localparam int ADDR_EX_BRANCH_TAKEN = 13'd7115;

    localparam int N_CHARS = 267;
    localparam int CTR_W     = 9;

    logic [8:0] char_ctr;

    // Helper functions: value --> ASCII
    function automatic [7:0] hex_digit (
        input logic [31:0] value,
        input int          nibble
    );
        logic [3:0] d;
        d = (value >> (nibble * 4)) & 4'hF;
        hex_digit = (d < 4'd10) ? (8'd48 + d) : (8'd55 + d);  // '0'-'9', 'A'-'F'
    endfunction

    function automatic [7:0] bin_digit (
        input logic value,
        input int   bit_idx
    );
        bin_digit = 8'd48 + ((value >> bit_idx) & 1'b1);  // '0' or '1'
    endfunction

    // Round-robin FSM - one char per cycle
    logic        wr_en;
    logic [12:0] wr_addr;
    logic [7:0]  wr_data;

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            char_ctr <= '0;
        end else begin
            char_ctr <= (char_ctr == N_CHARS - 1) ? '0 : char_ctr + 1'b1;
        end
    end

    always_comb begin
        // Default: no write
        wr_en   = 1'b0;
        wr_addr = '0;
        wr_data = 8'h20;  // space

        unique case (char_ctr)
        0: begin wr_en = 1'b1; wr_addr = ADDR_RU_DATA_WR_SRC + 0; wr_data = hex_digit(ru_data_wr_src, 0); end
        1: begin wr_en = 1'b1; wr_addr = ADDR_PC + 0; wr_data = hex_digit(pc, 7); end
        2: begin wr_en = 1'b1; wr_addr = ADDR_PC + 1; wr_data = hex_digit(pc, 6); end
        3: begin wr_en = 1'b1; wr_addr = ADDR_PC + 2; wr_data = hex_digit(pc, 5); end
        4: begin wr_en = 1'b1; wr_addr = ADDR_PC + 3; wr_data = hex_digit(pc, 4); end
        5: begin wr_en = 1'b1; wr_addr = ADDR_PC + 4; wr_data = hex_digit(pc, 3); end
        6: begin wr_en = 1'b1; wr_addr = ADDR_PC + 5; wr_data = hex_digit(pc, 2); end
        7: begin wr_en = 1'b1; wr_addr = ADDR_PC + 6; wr_data = hex_digit(pc, 1); end
        8: begin wr_en = 1'b1; wr_addr = ADDR_PC + 7; wr_data = hex_digit(pc, 0); end
        9: begin wr_en = 1'b1; wr_addr = ADDR_RS1_ADDR + 0; wr_data = hex_digit(rs1_addr, 1); end
        10: begin wr_en = 1'b1; wr_addr = ADDR_RS1_ADDR + 1; wr_data = hex_digit(rs1_addr, 0); end
        11: begin wr_en = 1'b1; wr_addr = ADDR_RS2_ADDR + 0; wr_data = hex_digit(rs2_addr, 1); end
        12: begin wr_en = 1'b1; wr_addr = ADDR_RS2_ADDR + 1; wr_data = hex_digit(rs2_addr, 0); end
        13: begin wr_en = 1'b1; wr_addr = ADDR_RD_ADDR + 0; wr_data = hex_digit(rd_addr, 1); end
        14: begin wr_en = 1'b1; wr_addr = ADDR_RD_ADDR + 1; wr_data = hex_digit(rd_addr, 0); end
        15: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 0; wr_data = hex_digit(instruction, 7); end
        16: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 1; wr_data = hex_digit(instruction, 6); end
        17: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 2; wr_data = hex_digit(instruction, 5); end
        18: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 3; wr_data = hex_digit(instruction, 4); end
        19: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 4; wr_data = hex_digit(instruction, 3); end
        20: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 5; wr_data = hex_digit(instruction, 2); end
        21: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 6; wr_data = hex_digit(instruction, 1); end
        22: begin wr_en = 1'b1; wr_addr = ADDR_INSTRUCTION + 7; wr_data = hex_digit(instruction, 0); end
        23: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 0; wr_data = hex_digit(next_pc, 7); end
        24: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 1; wr_data = hex_digit(next_pc, 6); end
        25: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 2; wr_data = hex_digit(next_pc, 5); end
        26: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 3; wr_data = hex_digit(next_pc, 4); end
        27: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 4; wr_data = hex_digit(next_pc, 3); end
        28: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 5; wr_data = hex_digit(next_pc, 2); end
        29: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 6; wr_data = hex_digit(next_pc, 1); end
        30: begin wr_en = 1'b1; wr_addr = ADDR_NEXT_PC + 7; wr_data = hex_digit(next_pc, 0); end
        31: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 0; wr_data = hex_digit(data_wr, 7); end
        32: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 1; wr_data = hex_digit(data_wr, 6); end
        33: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 2; wr_data = hex_digit(data_wr, 5); end
        34: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 3; wr_data = hex_digit(data_wr, 4); end
        35: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 4; wr_data = hex_digit(data_wr, 3); end
        36: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 5; wr_data = hex_digit(data_wr, 2); end
        37: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 6; wr_data = hex_digit(data_wr, 1); end
        38: begin wr_en = 1'b1; wr_addr = ADDR_DATA_WR + 7; wr_data = hex_digit(data_wr, 0); end
        39: begin wr_en = 1'b1; wr_addr = ADDR_RU_WR + 0; wr_data = bin_digit(ru_wr, 0); end
        40: begin wr_en = 1'b1; wr_addr = ADDR_IF_PC + 0; wr_data = hex_digit(if_pc, 7); end
        41: begin wr_en = 1'b1; wr_addr = ADDR_IF_PC + 1; wr_data = hex_digit(if_pc, 6); end
        42: begin wr_en = 1'b1; wr_addr = ADDR_IF_PC + 2; wr_data = hex_digit(if_pc, 5); end
        43: begin wr_en = 1'b1; wr_addr = ADDR_IF_PC + 3; wr_data = hex_digit(if_pc, 4); end
        44: begin wr_en = 1'b1; wr_addr = ADDR_IF_PC + 4; wr_data = hex_digit(if_pc, 3); end
        45: begin wr_en = 1'b1; wr_addr = ADDR_IF_PC + 5; wr_data = hex_digit(if_pc, 2); end
        46: begin wr_en = 1'b1; wr_addr = ADDR_IF_PC + 6; wr_data = hex_digit(if_pc, 1); end
        47: begin wr_en = 1'b1; wr_addr = ADDR_IF_PC + 7; wr_data = hex_digit(if_pc, 0); end
        48: begin wr_en = 1'b1; wr_addr = ADDR_IF_INSTRUCTION + 0; wr_data = hex_digit(if_instruction, 7); end
        49: begin wr_en = 1'b1; wr_addr = ADDR_IF_INSTRUCTION + 1; wr_data = hex_digit(if_instruction, 6); end
        50: begin wr_en = 1'b1; wr_addr = ADDR_IF_INSTRUCTION + 2; wr_data = hex_digit(if_instruction, 5); end
        51: begin wr_en = 1'b1; wr_addr = ADDR_IF_INSTRUCTION + 3; wr_data = hex_digit(if_instruction, 4); end
        52: begin wr_en = 1'b1; wr_addr = ADDR_IF_INSTRUCTION + 4; wr_data = hex_digit(if_instruction, 3); end
        53: begin wr_en = 1'b1; wr_addr = ADDR_IF_INSTRUCTION + 5; wr_data = hex_digit(if_instruction, 2); end
        54: begin wr_en = 1'b1; wr_addr = ADDR_IF_INSTRUCTION + 6; wr_data = hex_digit(if_instruction, 1); end
        55: begin wr_en = 1'b1; wr_addr = ADDR_IF_INSTRUCTION + 7; wr_data = hex_digit(if_instruction, 0); end
        56: begin wr_en = 1'b1; wr_addr = ADDR_BRANCH + 0; wr_data = bin_digit(branch, 0); end
        57: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 0; wr_data = hex_digit(rs1_data, 7); end
        58: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 1; wr_data = hex_digit(rs1_data, 6); end
        59: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 2; wr_data = hex_digit(rs1_data, 5); end
        60: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 3; wr_data = hex_digit(rs1_data, 4); end
        61: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 4; wr_data = hex_digit(rs1_data, 3); end
        62: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 5; wr_data = hex_digit(rs1_data, 2); end
        63: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 6; wr_data = hex_digit(rs1_data, 1); end
        64: begin wr_en = 1'b1; wr_addr = ADDR_RS1_DATA + 7; wr_data = hex_digit(rs1_data, 0); end
        65: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 0; wr_data = hex_digit(rs2_data, 7); end
        66: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 1; wr_data = hex_digit(rs2_data, 6); end
        67: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 2; wr_data = hex_digit(rs2_data, 5); end
        68: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 3; wr_data = hex_digit(rs2_data, 4); end
        69: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 4; wr_data = hex_digit(rs2_data, 3); end
        70: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 5; wr_data = hex_digit(rs2_data, 2); end
        71: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 6; wr_data = hex_digit(rs2_data, 1); end
        72: begin wr_en = 1'b1; wr_addr = ADDR_RS2_DATA + 7; wr_data = hex_digit(rs2_data, 0); end
        73: begin wr_en = 1'b1; wr_addr = ADDR_MEM_ALU_RESULT + 0; wr_data = hex_digit(mem_alu_result, 7); end
        74: begin wr_en = 1'b1; wr_addr = ADDR_MEM_ALU_RESULT + 1; wr_data = hex_digit(mem_alu_result, 6); end
        75: begin wr_en = 1'b1; wr_addr = ADDR_MEM_ALU_RESULT + 2; wr_data = hex_digit(mem_alu_result, 5); end
        76: begin wr_en = 1'b1; wr_addr = ADDR_MEM_ALU_RESULT + 3; wr_data = hex_digit(mem_alu_result, 4); end
        77: begin wr_en = 1'b1; wr_addr = ADDR_MEM_ALU_RESULT + 4; wr_data = hex_digit(mem_alu_result, 3); end
        78: begin wr_en = 1'b1; wr_addr = ADDR_MEM_ALU_RESULT + 5; wr_data = hex_digit(mem_alu_result, 2); end
        79: begin wr_en = 1'b1; wr_addr = ADDR_MEM_ALU_RESULT + 6; wr_data = hex_digit(mem_alu_result, 1); end
        80: begin wr_en = 1'b1; wr_addr = ADDR_MEM_ALU_RESULT + 7; wr_data = hex_digit(mem_alu_result, 0); end
        81: begin wr_en = 1'b1; wr_addr = ADDR_WB_INSTRUCTION + 0; wr_data = hex_digit(wb_instruction, 7); end
        82: begin wr_en = 1'b1; wr_addr = ADDR_WB_INSTRUCTION + 1; wr_data = hex_digit(wb_instruction, 6); end
        83: begin wr_en = 1'b1; wr_addr = ADDR_WB_INSTRUCTION + 2; wr_data = hex_digit(wb_instruction, 5); end
        84: begin wr_en = 1'b1; wr_addr = ADDR_WB_INSTRUCTION + 3; wr_data = hex_digit(wb_instruction, 4); end
        85: begin wr_en = 1'b1; wr_addr = ADDR_WB_INSTRUCTION + 4; wr_data = hex_digit(wb_instruction, 3); end
        86: begin wr_en = 1'b1; wr_addr = ADDR_WB_INSTRUCTION + 5; wr_data = hex_digit(wb_instruction, 2); end
        87: begin wr_en = 1'b1; wr_addr = ADDR_WB_INSTRUCTION + 6; wr_data = hex_digit(wb_instruction, 1); end
        88: begin wr_en = 1'b1; wr_addr = ADDR_WB_INSTRUCTION + 7; wr_data = hex_digit(wb_instruction, 0); end
        89: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 0; wr_data = hex_digit(imm_out, 7); end
        90: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 1; wr_data = hex_digit(imm_out, 6); end
        91: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 2; wr_data = hex_digit(imm_out, 5); end
        92: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 3; wr_data = hex_digit(imm_out, 4); end
        93: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 4; wr_data = hex_digit(imm_out, 3); end
        94: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 5; wr_data = hex_digit(imm_out, 2); end
        95: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 6; wr_data = hex_digit(imm_out, 1); end
        96: begin wr_en = 1'b1; wr_addr = ADDR_IMM_OUT + 7; wr_data = hex_digit(imm_out, 0); end
        97: begin wr_en = 1'b1; wr_addr = ADDR_IMM_SRC + 0; wr_data = hex_digit(imm_src, 0); end
        98: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_ADDR + 0; wr_data = 8'h30; end
        99: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_ADDR + 1; wr_data = 8'h30; end
        100: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_ADDR + 2; wr_data = 8'h30; end
        101: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_ADDR + 3; wr_data = 8'h30; end
        102: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_ADDR + 4; wr_data = 8'h30; end
        103: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_ADDR + 5; wr_data = 8'h30; end
        104: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_ADDR + 6; wr_data = hex_digit(wb_rd_addr, 1); end
        105: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_ADDR + 7; wr_data = hex_digit(wb_rd_addr, 0); end
        106: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_DATA + 0; wr_data = hex_digit(wb_rd_data, 7); end
        107: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_DATA + 1; wr_data = hex_digit(wb_rd_data, 6); end
        108: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_DATA + 2; wr_data = hex_digit(wb_rd_data, 5); end
        109: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_DATA + 3; wr_data = hex_digit(wb_rd_data, 4); end
        110: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_DATA + 4; wr_data = hex_digit(wb_rd_data, 3); end
        111: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_DATA + 5; wr_data = hex_digit(wb_rd_data, 2); end
        112: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_DATA + 6; wr_data = hex_digit(wb_rd_data, 1); end
        113: begin wr_en = 1'b1; wr_addr = ADDR_WB_RD_DATA + 7; wr_data = hex_digit(wb_rd_data, 0); end
        114: begin wr_en = 1'b1; wr_addr = ADDR_OPCODE + 0; wr_data = hex_digit(opcode, 1); end
        115: begin wr_en = 1'b1; wr_addr = ADDR_OPCODE + 1; wr_data = hex_digit(opcode, 0); end
        116: begin wr_en = 1'b1; wr_addr = ADDR_FUNCT3 + 0; wr_data = hex_digit(funct3, 0); end
        117: begin wr_en = 1'b1; wr_addr = ADDR_FUNCT7 + 0; wr_data = hex_digit(funct7, 1); end
        118: begin wr_en = 1'b1; wr_addr = ADDR_FUNCT7 + 1; wr_data = hex_digit(funct7, 0); end
        119: begin wr_en = 1'b1; wr_addr = ADDR_ID_PC + 0; wr_data = hex_digit(id_pc, 7); end
        120: begin wr_en = 1'b1; wr_addr = ADDR_ID_PC + 1; wr_data = hex_digit(id_pc, 6); end
        121: begin wr_en = 1'b1; wr_addr = ADDR_ID_PC + 2; wr_data = hex_digit(id_pc, 5); end
        122: begin wr_en = 1'b1; wr_addr = ADDR_ID_PC + 3; wr_data = hex_digit(id_pc, 4); end
        123: begin wr_en = 1'b1; wr_addr = ADDR_ID_PC + 4; wr_data = hex_digit(id_pc, 3); end
        124: begin wr_en = 1'b1; wr_addr = ADDR_ID_PC + 5; wr_data = hex_digit(id_pc, 2); end
        125: begin wr_en = 1'b1; wr_addr = ADDR_ID_PC + 6; wr_data = hex_digit(id_pc, 1); end
        126: begin wr_en = 1'b1; wr_addr = ADDR_ID_PC + 7; wr_data = hex_digit(id_pc, 0); end
        127: begin wr_en = 1'b1; wr_addr = ADDR_ID_INSTRUCTION + 0; wr_data = hex_digit(id_instruction, 7); end
        128: begin wr_en = 1'b1; wr_addr = ADDR_ID_INSTRUCTION + 1; wr_data = hex_digit(id_instruction, 6); end
        129: begin wr_en = 1'b1; wr_addr = ADDR_ID_INSTRUCTION + 2; wr_data = hex_digit(id_instruction, 5); end
        130: begin wr_en = 1'b1; wr_addr = ADDR_ID_INSTRUCTION + 3; wr_data = hex_digit(id_instruction, 4); end
        131: begin wr_en = 1'b1; wr_addr = ADDR_ID_INSTRUCTION + 4; wr_data = hex_digit(id_instruction, 3); end
        132: begin wr_en = 1'b1; wr_addr = ADDR_ID_INSTRUCTION + 5; wr_data = hex_digit(id_instruction, 2); end
        133: begin wr_en = 1'b1; wr_addr = ADDR_ID_INSTRUCTION + 6; wr_data = hex_digit(id_instruction, 1); end
        134: begin wr_en = 1'b1; wr_addr = ADDR_ID_INSTRUCTION + 7; wr_data = hex_digit(id_instruction, 0); end
        135: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 0; wr_data = hex_digit(dm_addr, 7); end
        136: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 1; wr_data = hex_digit(dm_addr, 6); end
        137: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 2; wr_data = hex_digit(dm_addr, 5); end
        138: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 3; wr_data = hex_digit(dm_addr, 4); end
        139: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 4; wr_data = hex_digit(dm_addr, 3); end
        140: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 5; wr_data = hex_digit(dm_addr, 2); end
        141: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 6; wr_data = hex_digit(dm_addr, 1); end
        142: begin wr_en = 1'b1; wr_addr = ADDR_DM_ADDR + 7; wr_data = hex_digit(dm_addr, 0); end
        143: begin wr_en = 1'b1; wr_addr = ADDR_EX_PC + 0; wr_data = hex_digit(ex_pc, 7); end
        144: begin wr_en = 1'b1; wr_addr = ADDR_EX_PC + 1; wr_data = hex_digit(ex_pc, 6); end
        145: begin wr_en = 1'b1; wr_addr = ADDR_EX_PC + 2; wr_data = hex_digit(ex_pc, 5); end
        146: begin wr_en = 1'b1; wr_addr = ADDR_EX_PC + 3; wr_data = hex_digit(ex_pc, 4); end
        147: begin wr_en = 1'b1; wr_addr = ADDR_EX_PC + 4; wr_data = hex_digit(ex_pc, 3); end
        148: begin wr_en = 1'b1; wr_addr = ADDR_EX_PC + 5; wr_data = hex_digit(ex_pc, 2); end
        149: begin wr_en = 1'b1; wr_addr = ADDR_EX_PC + 6; wr_data = hex_digit(ex_pc, 1); end
        150: begin wr_en = 1'b1; wr_addr = ADDR_EX_PC + 7; wr_data = hex_digit(ex_pc, 0); end
        151: begin wr_en = 1'b1; wr_addr = ADDR_DM_WDATA + 0; wr_data = hex_digit(dm_wdata, 7); end
        152: begin wr_en = 1'b1; wr_addr = ADDR_DM_WDATA + 1; wr_data = hex_digit(dm_wdata, 6); end
        153: begin wr_en = 1'b1; wr_addr = ADDR_DM_WDATA + 2; wr_data = hex_digit(dm_wdata, 5); end
        154: begin wr_en = 1'b1; wr_addr = ADDR_DM_WDATA + 3; wr_data = hex_digit(dm_wdata, 4); end
        155: begin wr_en = 1'b1; wr_addr = ADDR_DM_WDATA + 4; wr_data = hex_digit(dm_wdata, 3); end
        156: begin wr_en = 1'b1; wr_addr = ADDR_DM_WDATA + 5; wr_data = hex_digit(dm_wdata, 2); end
        157: begin wr_en = 1'b1; wr_addr = ADDR_DM_WDATA + 6; wr_data = hex_digit(dm_wdata, 1); end
        158: begin wr_en = 1'b1; wr_addr = ADDR_DM_WDATA + 7; wr_data = hex_digit(dm_wdata, 0); end
        159: begin wr_en = 1'b1; wr_addr = ADDR_EX_INSTRUCTION + 0; wr_data = hex_digit(ex_instruction, 7); end
        160: begin wr_en = 1'b1; wr_addr = ADDR_EX_INSTRUCTION + 1; wr_data = hex_digit(ex_instruction, 6); end
        161: begin wr_en = 1'b1; wr_addr = ADDR_EX_INSTRUCTION + 2; wr_data = hex_digit(ex_instruction, 5); end
        162: begin wr_en = 1'b1; wr_addr = ADDR_EX_INSTRUCTION + 3; wr_data = hex_digit(ex_instruction, 4); end
        163: begin wr_en = 1'b1; wr_addr = ADDR_EX_INSTRUCTION + 4; wr_data = hex_digit(ex_instruction, 3); end
        164: begin wr_en = 1'b1; wr_addr = ADDR_EX_INSTRUCTION + 5; wr_data = hex_digit(ex_instruction, 2); end
        165: begin wr_en = 1'b1; wr_addr = ADDR_EX_INSTRUCTION + 6; wr_data = hex_digit(ex_instruction, 1); end
        166: begin wr_en = 1'b1; wr_addr = ADDR_EX_INSTRUCTION + 7; wr_data = hex_digit(ex_instruction, 0); end
        167: begin wr_en = 1'b1; wr_addr = ADDR_DM_RDATA + 0; wr_data = hex_digit(dm_rdata, 7); end
        168: begin wr_en = 1'b1; wr_addr = ADDR_DM_RDATA + 1; wr_data = hex_digit(dm_rdata, 6); end
        169: begin wr_en = 1'b1; wr_addr = ADDR_DM_RDATA + 2; wr_data = hex_digit(dm_rdata, 5); end
        170: begin wr_en = 1'b1; wr_addr = ADDR_DM_RDATA + 3; wr_data = hex_digit(dm_rdata, 4); end
        171: begin wr_en = 1'b1; wr_addr = ADDR_DM_RDATA + 4; wr_data = hex_digit(dm_rdata, 3); end
        172: begin wr_en = 1'b1; wr_addr = ADDR_DM_RDATA + 5; wr_data = hex_digit(dm_rdata, 2); end
        173: begin wr_en = 1'b1; wr_addr = ADDR_DM_RDATA + 6; wr_data = hex_digit(dm_rdata, 1); end
        174: begin wr_en = 1'b1; wr_addr = ADDR_DM_RDATA + 7; wr_data = hex_digit(dm_rdata, 0); end
        175: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS1_DATA + 0; wr_data = hex_digit(ex_rs1_data, 7); end
        176: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS1_DATA + 1; wr_data = hex_digit(ex_rs1_data, 6); end
        177: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS1_DATA + 2; wr_data = hex_digit(ex_rs1_data, 5); end
        178: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS1_DATA + 3; wr_data = hex_digit(ex_rs1_data, 4); end
        179: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS1_DATA + 4; wr_data = hex_digit(ex_rs1_data, 3); end
        180: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS1_DATA + 5; wr_data = hex_digit(ex_rs1_data, 2); end
        181: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS1_DATA + 6; wr_data = hex_digit(ex_rs1_data, 1); end
        182: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS1_DATA + 7; wr_data = hex_digit(ex_rs1_data, 0); end
        183: begin wr_en = 1'b1; wr_addr = ADDR_DM_CTRL + 0; wr_data = hex_digit(dm_ctrl, 0); end
        184: begin wr_en = 1'b1; wr_addr = ADDR_STALL + 0; wr_data = bin_digit(stall, 0); end
        185: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS2_DATA + 0; wr_data = hex_digit(ex_rs2_data, 7); end
        186: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS2_DATA + 1; wr_data = hex_digit(ex_rs2_data, 6); end
        187: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS2_DATA + 2; wr_data = hex_digit(ex_rs2_data, 5); end
        188: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS2_DATA + 3; wr_data = hex_digit(ex_rs2_data, 4); end
        189: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS2_DATA + 4; wr_data = hex_digit(ex_rs2_data, 3); end
        190: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS2_DATA + 5; wr_data = hex_digit(ex_rs2_data, 2); end
        191: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS2_DATA + 6; wr_data = hex_digit(ex_rs2_data, 1); end
        192: begin wr_en = 1'b1; wr_addr = ADDR_EX_RS2_DATA + 7; wr_data = hex_digit(ex_rs2_data, 0); end
        193: begin wr_en = 1'b1; wr_addr = ADDR_DM_WR + 0; wr_data = hex_digit(dm_wr, 0); end
        194: begin wr_en = 1'b1; wr_addr = ADDR_LOAD_USE_HAZARD + 0; wr_data = bin_digit(load_use_hazard, 0); end
        195: begin wr_en = 1'b1; wr_addr = ADDR_EX_IMM + 0; wr_data = hex_digit(ex_imm, 7); end
        196: begin wr_en = 1'b1; wr_addr = ADDR_EX_IMM + 1; wr_data = hex_digit(ex_imm, 6); end
        197: begin wr_en = 1'b1; wr_addr = ADDR_EX_IMM + 2; wr_data = hex_digit(ex_imm, 5); end
        198: begin wr_en = 1'b1; wr_addr = ADDR_EX_IMM + 3; wr_data = hex_digit(ex_imm, 4); end
        199: begin wr_en = 1'b1; wr_addr = ADDR_EX_IMM + 4; wr_data = hex_digit(ex_imm, 3); end
        200: begin wr_en = 1'b1; wr_addr = ADDR_EX_IMM + 5; wr_data = hex_digit(ex_imm, 2); end
        201: begin wr_en = 1'b1; wr_addr = ADDR_EX_IMM + 6; wr_data = hex_digit(ex_imm, 1); end
        202: begin wr_en = 1'b1; wr_addr = ADDR_EX_IMM + 7; wr_data = hex_digit(ex_imm, 0); end
        203: begin wr_en = 1'b1; wr_addr = ADDR_BRANCH_FLUSH + 0; wr_data = bin_digit(branch_flush, 0); end
        204: begin wr_en = 1'b1; wr_addr = ADDR_TRAP_FLUSH + 0; wr_data = bin_digit(trap_flush, 0); end
        205: begin wr_en = 1'b1; wr_addr = ADDR_FLUSH + 0; wr_data = bin_digit(flush, 0); end
        206: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 0; wr_data = hex_digit(alu_a, 7); end
        207: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 1; wr_data = hex_digit(alu_a, 6); end
        208: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 2; wr_data = hex_digit(alu_a, 5); end
        209: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 3; wr_data = hex_digit(alu_a, 4); end
        210: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 4; wr_data = hex_digit(alu_a, 3); end
        211: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 5; wr_data = hex_digit(alu_a, 2); end
        212: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 6; wr_data = hex_digit(alu_a, 1); end
        213: begin wr_en = 1'b1; wr_addr = ADDR_ALU_A + 7; wr_data = hex_digit(alu_a, 0); end
        214: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS1_DATA + 0; wr_data = hex_digit(mem_rs1_data, 7); end
        215: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS1_DATA + 1; wr_data = hex_digit(mem_rs1_data, 6); end
        216: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS1_DATA + 2; wr_data = hex_digit(mem_rs1_data, 5); end
        217: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS1_DATA + 3; wr_data = hex_digit(mem_rs1_data, 4); end
        218: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS1_DATA + 4; wr_data = hex_digit(mem_rs1_data, 3); end
        219: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS1_DATA + 5; wr_data = hex_digit(mem_rs1_data, 2); end
        220: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS1_DATA + 6; wr_data = hex_digit(mem_rs1_data, 1); end
        221: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS1_DATA + 7; wr_data = hex_digit(mem_rs1_data, 0); end
        222: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 0; wr_data = hex_digit(alu_b, 7); end
        223: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 1; wr_data = hex_digit(alu_b, 6); end
        224: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 2; wr_data = hex_digit(alu_b, 5); end
        225: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 3; wr_data = hex_digit(alu_b, 4); end
        226: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 4; wr_data = hex_digit(alu_b, 3); end
        227: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 5; wr_data = hex_digit(alu_b, 2); end
        228: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 6; wr_data = hex_digit(alu_b, 1); end
        229: begin wr_en = 1'b1; wr_addr = ADDR_ALU_B + 7; wr_data = hex_digit(alu_b, 0); end
        230: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS2_DATA + 0; wr_data = hex_digit(mem_rs2_data, 7); end
        231: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS2_DATA + 1; wr_data = hex_digit(mem_rs2_data, 6); end
        232: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS2_DATA + 2; wr_data = hex_digit(mem_rs2_data, 5); end
        233: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS2_DATA + 3; wr_data = hex_digit(mem_rs2_data, 4); end
        234: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS2_DATA + 4; wr_data = hex_digit(mem_rs2_data, 3); end
        235: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS2_DATA + 5; wr_data = hex_digit(mem_rs2_data, 2); end
        236: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS2_DATA + 6; wr_data = hex_digit(mem_rs2_data, 1); end
        237: begin wr_en = 1'b1; wr_addr = ADDR_MEM_RS2_DATA + 7; wr_data = hex_digit(mem_rs2_data, 0); end
        238: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 0; wr_data = hex_digit(alu_res, 7); end
        239: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 1; wr_data = hex_digit(alu_res, 6); end
        240: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 2; wr_data = hex_digit(alu_res, 5); end
        241: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 3; wr_data = hex_digit(alu_res, 4); end
        242: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 4; wr_data = hex_digit(alu_res, 3); end
        243: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 5; wr_data = hex_digit(alu_res, 2); end
        244: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 6; wr_data = hex_digit(alu_res, 1); end
        245: begin wr_en = 1'b1; wr_addr = ADDR_ALU_RES + 7; wr_data = hex_digit(alu_res, 0); end
        246: begin wr_en = 1'b1; wr_addr = ADDR_EX_ALU_RESULT + 0; wr_data = hex_digit(ex_alu_result, 7); end
        247: begin wr_en = 1'b1; wr_addr = ADDR_EX_ALU_RESULT + 1; wr_data = hex_digit(ex_alu_result, 6); end
        248: begin wr_en = 1'b1; wr_addr = ADDR_EX_ALU_RESULT + 2; wr_data = hex_digit(ex_alu_result, 5); end
        249: begin wr_en = 1'b1; wr_addr = ADDR_EX_ALU_RESULT + 3; wr_data = hex_digit(ex_alu_result, 4); end
        250: begin wr_en = 1'b1; wr_addr = ADDR_EX_ALU_RESULT + 4; wr_data = hex_digit(ex_alu_result, 3); end
        251: begin wr_en = 1'b1; wr_addr = ADDR_EX_ALU_RESULT + 5; wr_data = hex_digit(ex_alu_result, 2); end
        252: begin wr_en = 1'b1; wr_addr = ADDR_EX_ALU_RESULT + 6; wr_data = hex_digit(ex_alu_result, 1); end
        253: begin wr_en = 1'b1; wr_addr = ADDR_EX_ALU_RESULT + 7; wr_data = hex_digit(ex_alu_result, 0); end
        254: begin wr_en = 1'b1; wr_addr = ADDR_MEM_INSTRUCTION + 0; wr_data = hex_digit(mem_instruction, 7); end
        255: begin wr_en = 1'b1; wr_addr = ADDR_MEM_INSTRUCTION + 1; wr_data = hex_digit(mem_instruction, 6); end
        256: begin wr_en = 1'b1; wr_addr = ADDR_MEM_INSTRUCTION + 2; wr_data = hex_digit(mem_instruction, 5); end
        257: begin wr_en = 1'b1; wr_addr = ADDR_MEM_INSTRUCTION + 3; wr_data = hex_digit(mem_instruction, 4); end
        258: begin wr_en = 1'b1; wr_addr = ADDR_MEM_INSTRUCTION + 4; wr_data = hex_digit(mem_instruction, 3); end
        259: begin wr_en = 1'b1; wr_addr = ADDR_MEM_INSTRUCTION + 5; wr_data = hex_digit(mem_instruction, 2); end
        260: begin wr_en = 1'b1; wr_addr = ADDR_MEM_INSTRUCTION + 6; wr_data = hex_digit(mem_instruction, 1); end
        261: begin wr_en = 1'b1; wr_addr = ADDR_MEM_INSTRUCTION + 7; wr_data = hex_digit(mem_instruction, 0); end
        262: begin wr_en = 1'b1; wr_addr = ADDR_ALU_OP + 0; wr_data = hex_digit(alu_op, 1); end
        263: begin wr_en = 1'b1; wr_addr = ADDR_ALU_OP + 1; wr_data = hex_digit(alu_op, 0); end
        264: begin wr_en = 1'b1; wr_addr = ADDR_BR_OP + 0; wr_data = hex_digit(br_op, 1); end
        265: begin wr_en = 1'b1; wr_addr = ADDR_BR_OP + 1; wr_data = hex_digit(br_op, 0); end
        266: begin wr_en = 1'b1; wr_addr = ADDR_EX_BRANCH_TAKEN + 0; wr_data = bin_digit(ex_branch_taken, 0); end
            default: ;  // no write
        endcase
    end

    assign vmem_wr_en   = wr_en;
    assign vmem_wr_addr = wr_addr;
    assign vmem_wr_data = {8'h0F, wr_data};  // ATTR_DYNAMIC + char

endmodule

