#!/usr/bin/env python3
# Generates rtl/shared/mem_config.vh with preprocessor macros for $readmemh path injection (ADR 025).

import argparse
import sys
from pathlib import Path

OUTPUT_PATH = Path("rtl/shared/mem_config.vh")

MEM_CONFIG_TEMPLATE = """\
// Generated by scripts/gen_mem_config.py - do not edit manually
`ifndef MEM_CONFIG_VH
`define MEM_CONFIG_VH

`define IMEM_FILE "{imem_path}"
`define DMEM_FILE "{dmem_path}"

`endif
"""


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate rtl/shared/mem_config.vh with `define macros for $readmemh. "
            ".mem files must have been produced by scripts/elf_to_mem.py."
        )
    )
    parser.add_argument(
        "--imem",
        type=Path,
        required=True,
        help="Path to the instruction memory .mem file (IMEM_FILE macro).",
    )
    parser.add_argument(
        "--dmem",
        type=Path,
        default=None,
        help=(
            "Path to the data memory .mem file (DMEM_FILE macro). "
            "Omit or leave empty to zero-initialize data memory."
        ),
    )
    return parser.parse_args()


def validate_mem_file(mem_path: Path, label: str) -> None:
    if not mem_path.exists():
        raise FileNotFoundError(
            f"{label} .mem file not found: {mem_path}\n"
            "Generate it first with: python3 scripts/elf_to_mem.py <bin> <depth> <out>"
        )
    if mem_path.suffix != ".mem":
        raise ValueError(
            f"{label} path does not have a .mem extension: {mem_path}\n"
            "Verify the path points to a file produced by elf_to_mem.py."
        )


def resolve_dmem_path(dmem_arg: Path | None) -> str:
    """Returns the dmem path string for the template, or empty string if omitted."""
    if dmem_arg is None:
        return ""
    validate_mem_file(dmem_arg, "DMEM")
    return str(dmem_arg)


def render_mem_config(imem_path: Path, dmem_path: str) -> str:
    return MEM_CONFIG_TEMPLATE.format(
        imem_path=imem_path,
        dmem_path=dmem_path,
    )


def write_header_file(content: str) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="ascii")


def generate_mem_config(imem_path: Path, dmem_arg: Path | None) -> None:
    validate_mem_file(imem_path, "IMEM")
    dmem_path = resolve_dmem_path(dmem_arg)
    header_content = render_mem_config(imem_path, dmem_path)
    write_header_file(header_content)

    dmem_status = dmem_path if dmem_path else "(empty - data memory zero-initialized)"
    print(f"[gen_mem_config] Written: {OUTPUT_PATH}")
    print(f"[gen_mem_config]   IMEM_FILE = {imem_path}")
    print(f"[gen_mem_config]   DMEM_FILE = {dmem_status}")


def main() -> None:
    args = parse_arguments()
    try:
        generate_mem_config(args.imem, args.dmem)
    except (FileNotFoundError, ValueError) as error:
        print(f"[gen_mem_config] ERROR: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()