#!/usr/bin/env python3
"""
gen_screen_writer.py — Auto-generates screen_writer SystemVerilog from
fields.json produced by gen_screen_mif.py.

The generated module uses character-level round-robin writes:
each clock cycle updates exactly ONE character cell.  Total refresh
= sum(widths) cycles.  At 50 MHz, even 200 chars × 20 ns = 4 µs,
which is ~4000× faster than a VGA frame (16.7 ms).
"""

import argparse
import json
import sys
from pathlib import Path


def generate_rtl(fields: list, mode: str) -> str:
    """Produce the SystemVerilog source for the screen writer."""

    # Keep only processor-level fields (skip register-file and memory tables)
    proc_fields = [
        f for f in fields
        if not f['name'].startswith('x') and
           not f['name'].startswith('data_memory_') and
           not f['name'].startswith('prog._memory_')
    ]

    # Build a flat list of character writes
    # Each entry: (char_index, field_name, field_bits, pos_in_field, nibble_or_bit, fmt)
    chars = []
    for f in proc_fields:
        name = f['name']
        width = f['width']
        fmt = f['fmt']
        bits = f['signal_bits']
        for pos in range(width):
            if fmt == 'hex':
                nibble = width - 1 - pos
                chars.append((name, bits, pos, nibble, 'hex'))
            else:
                bit = width - 1 - pos
                chars.append((name, bits, pos, bit, 'bin'))

    n_chars = len(chars)
    ctr_width = (n_chars - 1).bit_length() if n_chars > 1 else 1

    # Build parameter address constants
    params = '\n'.join(
        f"    localparam int ADDR_{f['name'].upper()} = 13'd{f['start_address']};"
        for f in proc_fields
    )

    # Build the case block: each entry writes one char
    cases = []
    for i, (name, bits, pos, idx, fmt) in enumerate(chars):
        addr = f"ADDR_{name.upper()} + {pos}"
        if fmt == 'hex':
            # For signals narrower than the display width, pad with '0' on the left
            # idx is the nibble from MSB to LSB
            if bits > (idx * 4):
                data_expr = f"hex_digit({name}, {idx})"
            else:
                data_expr = "8'h30"  # '0'
        else:
            if idx < bits:
                data_expr = f"bin_digit({name}, {idx})"
            else:
                data_expr = "8'h30"  # '0'

        cases.append(
            f"        {i}: begin wr_en = 1'b1; wr_addr = {addr}; wr_data = {data_expr}; end"
        )

    case_block = '\n'.join(cases)

    # Build input port list
    port_names = sorted(set(f['name'] for f in proc_fields))
    port_widths = {f['name']: f['signal_bits'] for f in proc_fields}

    input_ports = '\n'.join(
        f"    input logic [{port_widths[n]-1}:0] {n},"
        for n in port_names
    )

    sv = f'''// screen_writer_{mode} — auto-generated by gen_screen_writer.py
// Character-level round-robin.  Refresh = {n_chars} cycles @ 50 MHz.

module screen_writer_{mode} (
    input logic        clk,
    input logic        rst_n,

    // Processor signals (all values to be displayed)
{input_ports}

    // Video memory port (write-only, processor clock domain)
    output logic        vmem_wr_en,
    output logic [12:0] vmem_wr_addr,
    output logic [15:0] vmem_wr_data
);

    // -----------------------------------------------------------------------
    // Field address map (from fields.json)
    // -----------------------------------------------------------------------
{params}

    localparam int N_CHARS = {n_chars};
    localparam int CTR_W     = {ctr_width};

    logic [{ctr_width-1}:0] char_ctr;

    // -----------------------------------------------------------------------
    // Helper functions: value → ASCII
    // -----------------------------------------------------------------------
    function automatic [7:0] hex_digit (
        input logic [31:0] value,
        input int          nibble
    );
        logic [3:0] d;
        d = (value >> (nibble * 4)) & 4'hF;
        hex_digit = (d < 4'd10) ? (8'd48 + d) : (8'd55 + d);  // '0'-'9', 'A'-'F'
    endfunction

    function automatic [7:0] bin_digit (
        input logic value,
        input int   bit_idx
    );
        bin_digit = 8'd48 + ((value >> bit_idx) & 1'b1);  // '0' or '1'
    endfunction

    // -----------------------------------------------------------------------
    // Round-robin FSM — one char per cycle
    // -----------------------------------------------------------------------
    logic        wr_en;
    logic [12:0] wr_addr;
    logic [7:0]  wr_data;

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            char_ctr <= '0;
        end else begin
            char_ctr <= (char_ctr == N_CHARS - 1) ? '0 : char_ctr + 1'b1;
        end
    end

    always_comb begin
        // Default: no write
        wr_en   = 1'b0;
        wr_addr = '0;
        wr_data = 8'h20;  // space

        unique case (char_ctr)
{case_block}
            default: ;  // no write
        endcase
    end

    assign vmem_wr_en   = wr_en;
    assign vmem_wr_addr = wr_addr;
    assign vmem_wr_data = {{8'h0F, wr_data}};  // ATTR_DYNAMIC + char

endmodule
'''
    return sv


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--fields-json', required=True)
    ap.add_argument('--out-rtl', required=True)
    ap.add_argument('--mode', required=True, choices=['single_cycle', 'pipeline'])
    args = ap.parse_args()

    with open(args.fields_json) as fp:
        data = json.load(fp)

    rtl = generate_rtl(data['fields'], args.mode)

    Path(args.out_rtl).write_text(rtl)
    print(f'Generated {args.out_rtl} with {len(data["fields"])} fields')
    return 0


if __name__ == '__main__':
    sys.exit(main())
