#!/usr/bin/env python3
# Generates rtl/shared/mem_config.vh with preprocessor macros for $readmemh path injection (ADR 025).
#
# The path written into the header is the one tools (iverilog, Quartus) use
# when resolving $readmemh filenames.  Tools resolve relative paths against
# their own working directory.  Pass --relative-to <tool-cwd> to
# automatically compute a relative path from the tool's working directory to
# the .mem file.

import argparse
import os
import sys
from pathlib import Path


MEM_CONFIG_TEMPLATE = """\
// Generated by scripts/gen_mem_config.py - do not edit manually
`ifndef MEM_CONFIG_VH
`define MEM_CONFIG_VH

`define IMEM_FILE "{imem_path}"
`define DMEM_FILE "{dmem_path}"

`endif
"""


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate rtl/shared/mem_config.vh with `define macros for $readmemh. "
            ".mem files must have been produced by scripts/elf_to_mem.py."
        )
    )
    parser.add_argument(
        "--imem",
        type=str,
        required=True,
        help="Path to the instruction memory .mem file (IMEM_FILE macro).",
    )
    parser.add_argument(
        "--dmem",
        type=str,
        default=None,
        help="Path to the data memory .mem file (DMEM_FILE macro).",
    )
    parser.add_argument(
        "--relative-to",
        type=str,
        default=None,
        dest="relative_to",
        help=(
            "Tool working directory.  When provided, --imem and --dmem are "
            "converted to paths relative to this directory before being "
            "written into the header.  Omit to write paths verbatim "
            "(backward-compatible behaviour).  Forward slashes are used "
            "regardless of platform."
        ),
    )
    parser.add_argument(
        "--validate-linux-path",
        type=str,
        default=None,
        dest="validate_imem",
        help=(
            "Linux path used only for existence validation. "
            "Use when --imem contains a Windows path (WSL scenario)."
        ),
    )
    parser.add_argument(
        "--validate-linux-dmem",
        type=str,
        default=None,
        dest="validate_dmem",
        help="Linux path for dmem existence validation (WSL scenario).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path for mem_config.vh. Defaults to rtl/shared/mem_config.vh relative to repo root.",
    )
    return parser.parse_args()


def validate_mem_file(sim_path: str, linux_path: str | None, label: str) -> None:
    """
    Validate that the .mem file exists.
    Uses linux_path for existence check when provided (WSL case where
    sim_path is a Windows path that Python on Linux cannot stat).
    Falls back to sim_path when linux_path is None (native Linux).
    """
    check_path = Path(linux_path) if linux_path else Path(sim_path)
    if not check_path.exists():
        raise FileNotFoundError(
            f"{label} .mem file not found: {check_path}\n"
            "Generate it first with: python3 scripts/elf_to_mem.py <bin> <depth> <out>"
        )
    if not sim_path.endswith(".mem"):
        raise ValueError(
            f"{label} path does not have a .mem extension: {sim_path}\n"
            "Verify the path points to a file produced by elf_to_mem.py."
        )


def _resolve_path(raw: str, relative_to: str | None) -> str:
    """
    Convert *raw* to the form that should be written into mem_config.vh.

    If *relative_to* is given, compute a relative path from that directory
    to *raw* (using forward slashes).  Otherwise return *raw* unchanged.
    """
    if relative_to is None:
        return raw
    return os.path.relpath(raw, start=relative_to).replace("\\", "/")


def render_mem_config(imem_path: str, dmem_path: str) -> str:
    return MEM_CONFIG_TEMPLATE.format(
        imem_path=imem_path,
        dmem_path=dmem_path,
    )


def write_header_file(content: str) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="ascii")


def generate_mem_config(
    imem_sim: str,
    dmem_sim: str | None,
    validate_imem: str | None,
    validate_dmem: str | None,
    relative_to: str | None,
) -> None:
    validate_mem_file(imem_sim, validate_imem, "IMEM")

    dmem_raw = ""
    if dmem_sim is not None:
        validate_mem_file(dmem_sim, validate_dmem, "DMEM")
        dmem_raw = dmem_sim

    # Resolve paths: if --relative-to is given, emit relative paths;
    # otherwise emit verbatim.
    imem_path = _resolve_path(imem_sim, relative_to)
    dmem_path = _resolve_path(dmem_raw, relative_to) if dmem_raw else ""

    header_content = render_mem_config(imem_path, dmem_path)
    write_header_file(header_content)

    dmem_status = dmem_path if dmem_path else "(empty - data memory zero-initialized)"
    print(f"[gen_mem_config] Written: {OUTPUT_PATH}")
    print(f"[gen_mem_config]   IMEM_FILE = {imem_path}")
    print(f"[gen_mem_config]   DMEM_FILE = {dmem_status}")


def main() -> None:
    args = parse_arguments()
    global OUTPUT_PATH
    if args.out:
        OUTPUT_PATH = args.out
    else:
        OUTPUT_PATH = Path(__file__).resolve().parents[1] / "rtl" / "shared" / "mem_config.vh"
    try:
        generate_mem_config(
            args.imem,
            args.dmem,
            args.validate_imem,
            args.validate_dmem,
            args.relative_to,
        )
    except (FileNotFoundError, ValueError) as error:
        print(f"[gen_mem_config] ERROR: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()